# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Theme Minim"
license = "MIT"
licenselink = "https://github.com/kaiiiz/hugo-theme-minim/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "You-Kai Zheng"
  homepage = "https://github.com/kaiiiz/"
