name = "Artisan"
license = "MIT"
licenselink = "https://github.com/kaiiiz/hugo-theme-artisan/blob/main/LICENSE"
description = ""
homepage = "http://example.com/"
tags = ["blog", "simple", "clean", "tailwindcss", "personal", "responsive", "customizable"]
features = ["multiple layout built-in"]
min_version = "0.78.0"

[author]
  name = "You-Kai Zheng"
  homepage = "https://github.com/kaiiiz/"
