name = "Monochrome"
license = "MIT"
licenselink = "https://github.com/kaiiiz/hugo-theme-monochrome/blob/main/LICENSE"
description = "Garytr is a clean, responsive, and programmer-friendly hugo theme"
homepage = "https://github.com/kaiiiz/hugo-theme-monochrome/"
tags = ["blog", "simple", "clean", "tailwindcss", "minimal", "responsive", "customizable", "search", "dark mode"]
features = ["Clean UI with small resources", "Responsive layout", "Dark mode", "Multiple layouts built-in", "Nested navbar", "Multilingual mode", "Syntax Highlighting with copy feature", "Site Search", "SEO-friendly", "MathJax Integration", "Useful shortcodes"]
min_version = "0.78.0"

[author]
  name = "You-Kai Zheng"
  homepage = "https://github.com/kaiiiz/"
