name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'
          extended: true

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup PostCSS
        run: npm install -g postcss && npm install -g postcss-cli && npm install -g autoprefixer

      - name: Setup Theme Dependency
        run: npm install

      - name: Setup public
        run: git worktree add -B gh-pages public origin/gh-pages

      - name: Clean public
        run: rm -rf public/*

      - name: Build
        run: hugo -s exampleSite --themesDir=../.. --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
